// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whwytlhysjiytcepufhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indod3l0bGh5c2ppeXRjZXB1Zmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODczMDIsImV4cCI6MjA2NTU2MzMwMn0.vBkCW5P0LA16UsxSJQdaqiLfOaUGQDL6XMiB-qkikh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);